name: hw2_env
dependencies:
  - python=3.8
  - pip
  - pip:
    - numpy==1.20.3
    - pandas==1.2.4
    - torch==1.9.0
    - torchvision==0.10.0
    - matplotlib==3.4.2
    - Pillow==8.2.0
    - opencv-python==4.5.2.54
